require(... .. ".alpha")
require(... .. ".autocommands")
require(... .. ".autopairs")
require(... .. ".bufferline")
require(... .. ".cmp")
require(... .. ".comment")
require(... .. ".dap")
require(... .. ".gitsigns")
require(... .. ".illuminate")
require(... .. ".indentline")
require(... .. ".lualine")
require(... .. ".mini-surround")
require(... .. ".notify")
require(... .. ".nvim-tree")
require(... .. ".project")
require(... .. ".telescope")
require(... .. ".toggleterm")
require(... .. ".treesitter")
require(... .. ".whichkey")

require("better_escape").setup()
require("numbertoggle").setup()
require("impatient").enable_profile()
